# Generated by Django 5.1.7 on 2025-04-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_staff_remove_announcement_attention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
