# Generated by Django 5.1.7 on 2025-04-12 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_staff_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='firstname',
            new_name='completename',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='lastname',
        ),
    ]
