# Generated by Django 5.1.7 on 2025-04-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_scholar_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholar',
            old_name='profile',
            new_name='logo',
        ),
    ]
