# Generated by Django 5.1.7 on 2025-04-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_rename_profile_scholar_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.AddField(
            model_name='scholar',
            name='category',
            field=models.CharField(choices=[('Private', 'Private'), ('Government', 'Government')], default='private', max_length=255),
        ),
    ]
