# Generated by Django 5.1.7 on 2025-04-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_delete_uploadedfile_scholar_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='category',
            field=models.CharField(choices=[('Private', 'Private'), ('Government', 'Government')], default='select', max_length=255),
        ),
    ]
