# Generated by Django 5.1.7 on 2025-04-28 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_scholar_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='status',
        ),
    ]
