# Generated by Django 5.1.7 on 2025-05-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_remove_announcement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
