# Generated by Django 5.1.7 on 2025-05-16 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_announcement_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='deleted',
            new_name='is_deleted',
        ),
    ]
